package com.eland.android.eoas.Model


/**
 * Created by liu.wenbin on 15/11/10.
 */
object Constant {
    val GLOBLE_SETTING = "GLOBLE_SETTING"
    val LOGIN_SUCCESS = "LOGIN_SUCCESS"
    val LOGINID = "LOGINID"

    val LOGINID_EMAIL = "LOGINID_EMAIL"
    val LOGINID_USERNAME = "LOGINID_USERNAME"
    val LOGINID_CELLNO = "LOGINID_CELLNO"

    val REG_AUTO = "REG_AUTO"
    val EOAS_CACHE = "EOAS_CACHE"
    val EOAS_REGAUTO = "EOAS_REGAUTO"
    val EOAS_CONTACT = "EOAS_CONTACT"
    val EOAS_RECEIVE = "EOAS_RECEIVE"
    val EOAS_PUSHID = "EOAS_PUSHID"
    val EOAS_THEME = "EOAS_THEME"
    val EOAS_ISCHANGINGTHEME = "EOAS_ISCHANGINGTHEME"
    val EOAS_IP = "EOAS_IP"
    val LOGINRESPONE = "LOGINRESPONE"
    val EMPDI = "EMPID"
    val SHOPCODE = "SHOPCODE"

    val DEVICEID = "DEVICEID"
}
